### ISSUE TITLE
add copyright notice to individual files?

### ISSUE THREAD

**Issue by barroit** [Caishangqi/charming-realm-system#1]
A copyright notice is a notice of statutorily prescribed form that informs users of the underlying claim to [copyright](https://en.m.wikipedia.org/wiki/Copyright) ownership in a published work.

An example copyright notice prefixed by a SPDX license identifier could be:
```
// SPDX-License-Identifier: $IDENTIFIER
/*
 * Copyright $YEAR $NAME
 *
 * Contact: $ADDRESS
 */
```

Good luck ;)

**Comment by Caishangqi** [comment]
i'm chinese

**Comment by barroit** [comment]
\> i'm chinese

版权声明是法定形式的通知，用于告知用户对已出版作品的版权所有权的基本主张。

以 SPDX 许可证标识符为前缀的版权声明示例如下：

```
// SPDX-许可证-标识符：$标识符
/*
* 版权 $年份 $名字
*
* 联络：$地址
*/
```

**Comment by Caishangqi** [comment]
> > i'm chinese
> 
> 版权声明是法定形式的通知，用于告知用户对已出版作品的版权所有权的基本主张。
> 
> 以 SPDX 许可证标识符为前缀的版权声明示例如下：
> 
> ```
> // SPDX-许可证-标识符：$标识符
> /*
> * 版权 $年份 $名字
> *
> * 联络：$地址
> */
> ```

I mean Chinese are not bound by copyright :)

**Comment by barroit** [comment]
> > > i'm chinese
> > 
> > 
> > 版权声明是法定形式的通知，用于告知用户对已出版作品的版权所有权的基本主张。
> > 以 SPDX 许可证标识符为前缀的版权声明示例如下：
> > ```
> > // SPDX-许可证-标识符：$标识符
> > /*
> > * 版权 $年份 $名字
> > *
> > * 联络：$地址
> > */
> > ```
> 
> I mean Chinese are not bound by copyright :)

Shabi
